### ISSUE TITLE
DEV MVP 33 - Update gcc and clang version in u16cppall

### ISSUE THREAD

**Issue by raksha78** [dry-dock/u16cppall#8]
FROM https://github.com/Shippable/pm/issues/8613

    Update u16cppall to have the following versions.
        gcc - 7.1
        clang - 4.0.0

Test

    Test if gcc and clang versions are installed correctly.

Docs & Samples

Update docs with the version of gcc and clang installed on machine image
Release

Update release docs.

**Comment by kanthchandra** [comment]
this this done closing.
